const CommonObjects = function ()  {
    this.howToPlayButton = '[data-test=onboarding-intro-start-button]';
    this.howToPlaySkipButton = '[data-test=onboarding-skip-button]';
    this.busted = '[data-test="bust-text"]';
    this.betConfirmingSpinnerText = '[data-test="bet-confirming-container"]';
    this.gameScreen = '[data-test="game-container"]';
    this.betReturn = '[data-test="bet-return"]';
    this.menu = '[data-test="menu"]';
    this.gameNumberMultiplier = '[data-test="multiplier"]';
    this.confirmingBetScreen = '[data-test="bet-confirming-container"]';
    this.betConfirmingText = '[data-test="bet-confirming-text"]';
    this.confirmationSpinner = '[data-test="bet-confirming-icon"]';
    this.betAcceptedContainer = '[data-test="bet-accepted-container"]';
    this.betAcceptedText = '[data-test="bet-accepted-text"]';
    this.betAcceptedIcon = '[data-test="bet-accepted-icon"]';
    this.placeBetTimer = '[data-test="place-bet-timer"]';
    this.placeBetTimerText = '[data-test="place-bet-delay-text"]';
    this.autobetTimerText = '[data-test="auto-bet-delay-text"]';
    this.nextRoundTimer = '[data-test="next-round-timer"]';
    this.nextRoundTimerText = '[data-test="next-round-text"]';
    this.betTab = '[data-test="bet-tab"]';
    this.playersTab = '[data-test="players-tab"]';
    this.historyTab = '[data-test="history-tab"]';
    this.betTabContainer = '[data-test="tab-content-container"]';
    this.historyTabContainer = '[data-test="game-history-table"]';
    this.playersTabContainer = '[data-test="live-bets-table"]';
    this.historyTable = ['data-test="game-history-table-body"'];
    this.tabsContainer = '[data-test="tab-content-container"]';
    this.multiplier = '[data-test="bet-return"]';
    this.cashedOutInfo = '[data-test="cashed-out-info"]';
    this.cashedOutReturn = '[data-test="cashed-out-return"]';
    this.cashedOutMultiplier = '[data-test="cashed-out-multiplier"]';
    this.winToast = '[data-test="cashed-out-toast"]';
    this.toastLeftArrow = '[data-test="cashed-out-toast-left-arrows"]';
    this.toastRightArrow = '[data-test="cashed-out-toast-right-arrows"]';
    this.toastText = '[data-test="cashed-out-toast-message"]';
    this.errorWrapper = '[data-test="bet-error-wrapper"]';
    this.errorIcon = '[data-test="error-alert-icon"]';
    this.errorTitle = '[data-test="error-alert-title"]';
    this.errorDescription = '[data-test="error-alert-description"]';
    this.errorCloseButton = '[data-test="error-alert-close-button"]';
    this.bustValue = '[data-test="multiplier"]:first';
    this.historyOne = '[data-test="game-history-table-body"] tr td';
    this.historyFirstStake = '#root > main > section.sc-dqBHgY.kmpGTI > section.sc-gxMtzJ.fPKxfA > div > table > tbody > tr:nth-child(1) > td:nth-child(3)';    
    this.autoCashoutGameValue = '[data-test="auto-cashout-status-value"]';
    this.autoBetGameValue = '[data-test="auto-bet-status-count"]';
    this.lastGameItemList = '[data-test="last-games-list"] li';
    this.balanceAmount = '[data-test="balance-amount"]';
    this.balanceTitle = '[data-test="balance-title"]';
    this.betValue = '[data-test="bet-amount"]';
    this.betTitle = '[data-test="bet-title"]';
    this.lastWinTitle = '[data-test="last-win-title"]';
    this.lastWinValue = '[data-test="last-win-amount"]';
};

module.exports = CommonObjects;