const CommonObjects = function ()  {
    this.busted = '[data-test="bust-text"]';
    this.betConfirmingSpinnerText = '[data-test="bet-confirming-container"]';
    this.gameScreen = '[data-test="game-container"]';
    this.betReturn = '[data-test="bet-return"]';
    this.menu = '[data-test="menu"]';
    this.gameNumberMultiplier = '[data-test="multiplier"]';
    this.confirmingBetScreen = '[data-test="bet-confirming-container"]';
    this.betConfirmingText = '[data-test="bet-confirming-text"]';
    this.confirmationSpinner = '[data-test="bet-confirming-icon"]';
    this.betAcceptedContainer = '[data-test="bet-accepted-container"]';
    this.betAcceptedText = '[data-test="bet-accepted-text"]';
    this.betAcceptedIcon = '[data-test="bet-accepted-icon"]';
    this.placeBetTimer = '[data-test="place-bet-timer"]';
    this.placeBetTimerText = '[data-test="place-bet-delay-text"]';
    this.nextRoundTimer = '[data-test="next-round-timer"]';
    this.nextRoundTimerText = '[data-test="next-round-text"]';
    this.betTab = '[data-test="bet-tab"]';
    this.playersTab = '[data-test="players-tab"]';
    this.historyTab = '[data-test="history-tab"]';
    this.betTabContainer = '[data-test="tab-content-container"]';
    this.tabsContainer = '#root > main > section.sc-cSHVUG.hDUXUW > section.sc-kAzzGY.kdCQTQ > nav';
    this.multiplier = '[data-test="bet-return"]';
    this.cashedOutInfo = '[data-test="cashed-out-info"]';
    this.cashedOutReturn = '[data-test="cashed-out-return"]';
    this.cashedOutMultiplier = '[data-test="cashed-out-multiplier"]';
    this.winToast = '[data-test="cashed-out-toast"]';
};

module.exports = CommonObjects;